namespace GamerLibrary.Common.Domain
{
    public class BaseEntity
    {
        /// <summary>
        /// Unique identifier for this object, this value is autogenerated everytime that the entity is persisted.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// UTC Date time when the entity was created
        /// </summary>
        public DateTime CreatedDate { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Last UTC DateTime when the entity was updated
        /// It is null when the entity is created
        /// </summary>
        public DateTime? LastUpdatedDate { get; set; }
    }
}
